---
- name: Install Python Flask dependency
  pip:
     name: "{{ item }}"
     state: present
  with_items:
       - flask
       - flask-mysql

- name: Copy source code
  copy:
     src: app.py
     dest: /opt/app.py

- name: Start Web Server
#  command: /opt/app.py nohup flask run --host=0.0.0.0 &
#i  command: python /opt/app.py
  shell: "flask run"
  environment:
      FLASK_APP: /var/www/main.py
